// A PERSON HAS A PAGE, AND THE PAGE IS NOT A TEMPLATE.
//
// airraw.com shipped with four indexable URLs, so there was nothing to rank and
// nothing to post. These pages are the fix. Three things have to stay true or
// they are worse than nothing:
//
//   1. The copy is grammatical. It is generated by rewriting prompt text from
//      second person into first, and a broken pronoun on an indexed page is a
//      quality signal pointed at the whole domain. This walks EVERY entry of
//      EVERY dossier pool, not a sample.
//   2. Nothing public can spend money. Portraits are a paid API; a crawler hits
//      these pages thousands of times.
//   3. Kloom never sees them. It is the SFW brand the ad credit points at.
import { readFileSync } from "node:fs"

let fail = 0
const check = (c, l) => { console.log(`${c ? "ok  " : "FAIL"} ${l}`); if (!c) fail++ }

const cast = readFileSync("lib/airraw/public-cast.ts", "utf8")
const dossier = readFileSync("lib/airraw/dossier.ts", "utf8")
const page = readFileSync("app/who/[slug]/page.tsx", "utf8")
const layout = readFileSync("app/who/layout.tsx", "utf8")
const og = readFileSync("app/share/route.tsx", "utf8")
const sitemap = readFileSync("app/sitemap.ts", "utf8")

// ── the REAL rules, parsed out of the module rather than retyped ──────────
const block = cast.slice(cast.indexOf("const FIRST_PERSON"), cast.indexOf("/** Rewrite one dossier fact"))
const rules = [...block.matchAll(/\[\/(.+?)\/(g[i]?),\s*"(.*?)"\]/g)].map(([, src, flags, to]) => [new RegExp(src, flags), to])
check(rules.length >= 12, `the pronoun rules parse out of the source (${rules.length})`)
const say = (s) => rules.reduce((acc, [re, to]) => acc.replace(re, to), s)

const pool = (name) => {
  const i = dossier.indexOf(`const ${name}`)
  const body = dossier.slice(i, dossier.indexOf("\n]", i))
  return [...body.matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((m) => m[1])
}
const prompts = (n) => pool(n).filter((_, k) => k % 2 === 0)   // WORK/WHERE are [prompt, card]
const ALL = [...prompts("WORK"), ...prompts("WHERE"), ...pool("ON_MIND"), ...pool("OPINION"), ...pool("PEEVE"), ...pool("TELL")]
check(ALL.length >= 95, `every dossier pool entry is under test (${ALL.length})`)

// ── 1. no second person survives ──────────────────────────────────────────
const left = ALL.filter((s) => /\byou(?:'re|'ve|'ll|'d|r|rs|rself)?\b/i.test(say(s)))
check(left.length === 0, `no second-person pronoun survives the rewrite (${left.length} left: ${left.slice(0, 2).join(" | ")})`)

// ── 2. object case is right ───────────────────────────────────────────────
// A preposition's complement is ALWAYS object case, so "behind I" is a bug by
// construction — this is what caught "the window open behind I" before it shipped.
const prepI = ALL.map(say).filter((s) => /\b(on|to|behind|with|at|about|for|from|by|off|into|onto)\s+I\b/i.test(s))
check(prepI.length === 0, `no preposition is followed by "I" (${prepI.slice(0, 2).join(" | ")})`)
const verbI = ALL.map(say).filter((s) => /\b(shocks|texted|made|make|makes|tells|told|asks|asked)\s+I\b/i.test(s))
check(verbI.length === 0, `no transitive verb is followed by "I" (${verbI.slice(0, 2).join(" | ")})`)

// ── 3. the subject traps stay subjects ────────────────────────────────────
// "than" reads as a preposition and is not one here: "more than you admit" and
// "colder than you expected" are clauses. Converting them gave "more than me
// admit", which is why "than" is absent from the object rule.
const joined = ALL.map(say).join(" ~ ")
check(/more than I admit/.test(joined), '"more than you admit" stays a subject')
check(/colder than I expected/.test(joined), '"colder than you expected" stays a subject')
check(!/than me \w+ed\b|than me admit/.test(joined), 'no "than me <verb>" was produced')

// ── 4. the enumerated object phrases ──────────────────────────────────────
for (const want of [
  "nothing shocks me anymore",
  "people cry on me constantly",
  "everyone lies to me about their week",
  "the window open behind me",
  "someone texted me today",
  "someone made me feel obvious",
  "starting to make me reckless",
  "people who make me drag it out",
]) check(joined.includes(want), `object case: "${want}"`)

// "neither of you" is a phrase change, not a pronoun swap — alone it is "us".
check(/neither of us said anything/.test(joined), '"neither of you" becomes "neither of us", not "neither of me"')

// ── 5. a public page can never spend money ────────────────────────────────
for (const [name, src] of [["page", page], ["share card", og], ["cast", cast]]) {
  check(!/character-photo|\/api\//.test(src), `the ${name} never calls a paid image endpoint`)
}
check(/ImageResponse/.test(og), "the share card is drawn, not generated")
check(/runtime = "nodejs"/.test(og), "the card runs where AIRRAW_HOME is actually readable, so its brand gate works")
check(/IS_AIRRAW/.test(og) && /404/.test(og), "the card carries its own Kloom gate — it sits outside the /who layout")
check(/\/share\?i=/.test(page), "each page points its share card at that route")

// ── 6. bounded, and the bound is real ─────────────────────────────────────
check(/PUBLIC_CAST_SIZE/.test(sitemap), "the sitemap lists the public cast")
check(/i >= PUBLIC_CAST_SIZE\) return null/.test(cast), "an index past the cast resolves to nothing, so the bound is enforced")
check(/Math\.min\(5000/.test(cast), "the cast size is capped even if the env var says otherwise")

// ── 7. the slug tail is the identity ──────────────────────────────────────
// The descriptive middle can be rewritten without breaking links because only
// the trailing base-36 segment is read back.
check(/\.split\("-"\)\.pop\(\)/.test(cast), "only the slug's last segment is parsed")
const tailOf = (i) => (i >>> 0).toString(36)
const roundTrip = [0, 1, 35, 36, 599].every((i) => parseInt(tailOf(i), 36) === i)
check(roundTrip, "index → base36 tail → index round-trips")

// ── 8. Kloom never sees any of it ─────────────────────────────────────────
check(/AIRRAW_HOME === "1"/.test(layout) && /notFound\(\)/.test(layout), "/who 404s on every non-AIRRAW deployment")
check(/if \(AIRRAW\)/.test(sitemap), "the sitemap only offers these URLs on the AIRRAW host")

// ── 9. indexable and self-labelled ────────────────────────────────────────
check(/alternates: \{ canonical/.test(page), "each page declares a canonical URL")
check(/RTA-5042/.test(page), "each page carries the adult self-label for SafeSearch")
check(/application\/ld\+json/.test(page), "each page ships structured data")
check(/generateStaticParams/.test(page), "the pages are prerendered, not rendered per visitor")

console.log(fail === 0 ? "\nPASS" : `\nFAIL — ${fail}`)
process.exit(fail === 0 ? 0 : 1)
