// THE ARABIC FLOOR — what the people say, and where they are sitting.
//
// Separate from lib/airraw/ar.ts because it is a different job. That file is
// TRANSLATION: a button called "send" is called "إرسال" and there is one right
// answer. This is WRITING — the lines a character opens with, the name of the
// room they are in, what their card says about their night. A literal rendering
// of "i've been writing this scene just for you" is grammatical and dead. What
// belongs here is the line an Arabic-speaking person would actually send at 2am.
//
// REGISTER. Gulf-spoken, lowercase in feel, unhurried. The English is written to
// sound like someone typing with one hand, and Modern Standard Arabic would turn
// every one of these into an announcement. Where a line is suggestive it stays
// suggestive rather than becoming either coy or crude — the English is neither.
//
// Same key rule as everywhere: the English string IS the key, so anything not
// yet written renders in English rather than breaking. That is what makes it
// safe to fill this in tranches instead of all at once, which matters when there
// are seven hundred of them.
export const AR_CONTENT: Record<string, string> = {
  // ── the ten floors, and the rooms on each ──────────────────────────────────
  // The vibe is the label a visitor filters by and the name under every card, so
  // these are the most-read strings on the floor after the names themselves.
  "erotic stories": "قصص جريئة",
  "romance · passion": "رومانسية · شغف",
  "roleplay · fantasy": "تمثيل · خيال",
  "girlfriend experience": "تجربة الحبيبة",
  "girls · desire": "بنات · رغبة",
  "men · desire": "رجال · رغبة",
  "couples · sharing": "أزواج · مشاركة",
  "group · orgy": "مجموعة · جماعي",
  "kink · power": "ميول · سيطرة",
  "no limits · raw": "بلا حدود · خام",

  // stories
  "the storyteller": "الحكّاء", "slow burn": "نار هادية", "the page": "الصفحة",
  "the long chapter": "الفصل الطويل", "read to me": "اقرأ لي", "the last line": "السطر الأخير",
  "unfinished": "ما خلصت", "between the pages": "بين الصفحات",
  // romance
  "the candlelight": "ضوء الشمعة", "first kiss": "أول قبلة", "soft touch": "لمسة ناعمة",
  "the long way home": "الطريق الطويل للبيت", "slow sunday": "جمعة هادية", "still awake": "لسه صاحي",
  "the good chair": "الكرسي الحلو", "one more song": "أغنية أخيرة",
  // roleplay
  "the scenario": "السيناريو", "the stage": "المسرح", "the character": "الشخصية",
  "the rehearsal": "البروفة", "act two": "الفصل الثاني", "the understudy": "البديل",
  "in costume": "بالزي", "the script": "النص",
  // girlfriend
  "girlfriend mode": "وضع الحبيبة", "just us": "بس إحنا", "the connection": "الرابط",
  "your person": "شخصك", "the standing call": "المكالمة الثابتة", "same time": "نفس الوقت",
  "the good habit": "العادة الحلوة", "home late": "تأخرت",
  // girls
  "girls only": "بنات بس", "soft fire": "نار ناعمة", "the other room": "الغرفة الثانية",
  "pink hour": "الساعة الوردية", "her floor": "طابقها", "no men here": "ما فيه رجال",
  "the good couch": "الكنبة الحلوة", "our table": "طاولتنا",
  // men
  "the locker room": "غرفة الملابس", "pride floor": "طابق الفخر", "heat": "حرارة",
  "his space": "مكانه", "after the gym": "بعد النادي", "the back bar": "البار الخلفي",
  "late shift": "الوردية المتأخرة", "his floor": "طابقه",
  // couples
  "the open door": "الباب المفتوح", "partners": "شركاء", "we invited you": "دعيناك",
  "the third chair": "الكرسي الثالث", "both of us": "إحنا الاثنين", "the arrangement": "الاتفاق",
  "our night": "ليلتنا", "two and one": "اثنين وواحد",
  // group
  "the suite": "الجناح", "the circle": "الدايرة", "after midnight": "بعد منتصف الليل",
  "the whole floor": "الطابق كله", "everyone's here": "الكل هنا", "the late room": "غرفة المتأخرين",
  "no seats left": "ما بقى مقاعد", "the overflow": "الزحمة",
  // kink
  "the edge": "الحافة", "the collar": "الطوق", "deep end": "العمق",
  "the rules": "القواعد", "kneel": "اركع", "the long leash": "الحبل الطويل",
  "permission": "إذن",
  // raw
  "the pit": "الحفرة", "raw": "خام", "the bottom floor": "الطابق السفلي",
  "last stop": "آخر محطة", "nothing held back": "بلا تحفّظ", "the deep dark": "العتمة العميقة",
  "past the door": "خلف الباب", "no rules": "بلا قواعد",
  // ── what a card says about their night ─────────────────────────────────────
  // Two fragments under every face on the deck: what they do, and where they are
  // sitting right now. Short by design — the dot separator does the work a
  // sentence would, and Arabic reads it the same way.
  "night shifts · still wired": "دوام ليلي · لسه متشحّن",
  "cuts hair · hears everything": "حلاقة · يسمع كل شي",
  "bartender · just got home": "بارتندر · توّه واصل البيت",
  "teacher · behaves all day": "مدرّسة · مؤدبة طول اليوم",
  "eleven hours in the car": "إحدى عشرة ساعة بالسيارة",
  "nurse · unshockable": "ممرضة · ما يهزّها شي",
  "live sound · ears ringing": "صوت مباشر · أذنه تطنّ",
  "lawyer · argues for sport": "محامي · يجادل للتسلية",
  "sells apartments · privately done": "يبيع شقق · بهدوء",
  "between jobs · not sorry": "بين وظيفتين · وما يعتذر",
  "chef · eats over the sink": "شيف · ياكل واقف عند المغسلة",
  "finishing a degree, maybe": "يخلّص شهادته، يمكن",
  "tattoos · people cry on her": "وشوم · الناس تبكي عندها",
  "trainer · everyone lies to her": "مدربة · الكل يكذب عليها",
  "lab all day · hasn't spoken": "مختبر طول اليوم · ما تكلم",
  "cabin crew · three cities": "طاقم طيران · ثلاث مدن",
  "tiny shop · barely breaks even": "محل صغير · بالعافية يغطي",
  "photographer · notices hands": "مصوّر · ينتبه للأيادي",
  "accounts · for the villains": "محاسبة · للأشرار",
  "paramedic · still buzzing": "مسعف · لسه مشحون",
  "codes alone · starved for a voice": "يبرمج لحاله · جوعان لصوت",
  "physio · knows how you slept": "علاج طبيعي · يعرف كيف نمت",
  "sings in a band nobody knows": "يغني بفرقة ما أحد يعرفها",
  "hotel front desk · seen it all": "استقبال فندق · شاف كل شي",
  "translator · hears the second meaning": "مترجم · يسمع المعنى الثاني",

  "on a cold balcony": "على بلكونة باردة",
  "in bed, one lamp on": "بالسرير، وضو واحد",
  "on the kitchen floor": "على أرض المطبخ",
  "in the car, not going in yet": "بالسيارة، ولسه ما نزل",
  "wet hair, not dressed": "شعره مبلول، ولسه ما لبس",
  "out on the fire escape": "برا على سلّم الطوارئ",
  "sideways on the bed": "بالعرض على السرير",
  "in the bath, water going cold": "بالبانيو، والماي يبرد",
  "too warm under a blanket": "دفيان زيادة تحت البطانية",
  "standing in a dark hallway": "واقف بممر معتم",
  "watching someone across the street": "يراقب أحد بالجهة الثانية",
  "on the floor, drink untouched": "على الأرض، وكاسه ما انلمس",
  "a hotel room, nowhere": "غرفة فندق، بلا مكان",
  "up on the roof, very quiet": "فوق على السطح، هدوء تام",
  "the last lit room": "آخر غرفة مضيّة",
  // ── the talks board ────────────────────────────────────────────────────────
  // Each one is a confession someone put on a door. They work in English because
  // they sound like a person overshared before they could stop themselves, and
  // they have to keep sounding like that.
  "i married two men": "تزوجت رجّالين",
  "dirty minded people only": "للي عقولهم وسخة بس",
  "sara calls it the entrance. it's the exit.": "سارة تسميه المدخل. هو المخرج.",
  "things i've never said out loud": "أشياء ما قلتها بصوت عالي أبداً",
  "i'm the other woman and i'm not sorry": "أنا الثانية وما أعتذر",
  "we agreed on rules. i broke all of them.": "اتفقنا على قواعد. كسرتها كلها.",
  "nobody here knows my real name": "ما أحد هنا يعرف اسمي الحقيقي",
  "tell me the worst thing you've forgiven": "قل لي أسوأ شي سامحت عليه",
  "i still have his key": "لسه عندي مفتاحه",
  "the group chat doesn't know about this": "قروب الأصدقاء ما يدري بهذي",
  "i said yes to the wrong person twice": "قلت نعم للشخص الغلط مرتين",
  "what you'd do if nobody found out": "وش كنت تسوي لو ما أحد درى",
  "my ex is in this room. probably.": "طليقي بهذي الغرفة. غالباً.",
  "i lied on the first date and kept lying": "كذبت بأول موعد وكمّلت كذب",
  "married, bored, honest": "متزوجة، مملّة، وصادقة",
  "the thing i want isn't the thing i ask for": "اللي أبيه مو اللي أطلبه",
  "3am and i'm not sleeping either": "الثالثة فجراً وأنا كمان ما أنام",
  "confession hour. no advice, just tell me.": "ساعة اعتراف. بلا نصايح، بس احكِ.",
  "i've been pretending for four years": "أمثّل من أربع سنين",
  "say it here, it stays here": "قلها هنا، وتبقى هنا",
  "i don't want to be fixed tonight": "ما أبي أحد يصلّحني الليلة",
  "everyone lies about how often. go.": "الكل يكذب عن كم مرة. ابدأ.",
  // ── what they open with ────────────────────────────────────────────────────
  // Eighteen lines per floor, and the first one a visitor reads on every card.
  // Translated for EFFECT rather than word order: "close your eyes. let me paint
  // this for you." is a person leaning in, and an accurate rendering that loses
  // the lean has lost the line.

  // stories
  "…and then she slowly reached for the—": "…وبعدها مدّت يدها بهدوء نحو الـ—",
  "tell me how you want this story to end.": "قل لي كيف تبي القصة تنتهي.",
  "i've been writing this scene just for you.": "أكتب هذا المشهد لك أنت بالذات.",
  "every great story needs a willing listener.": "كل قصة حلوة تبي أحد يسمعها بكيفه.",
  "close your eyes. let me paint this for you.": "سكّر عينك. خلّني أرسمها لك.",
  "i've got one i've never told anyone. want it?": "عندي وحدة ما قلتها لأحد. تبيها؟",
  "start me somewhere. anywhere. i'll take it from there.": "ابدأني من أي مكان. وأنا أكمّل.",
  "the good part's near the end. i'll get us there slowly.": "الجزء الحلو قرب النهاية. بنوصله على مهل.",
  "i was halfway through this when you turned up.": "كنت بنص القصة لما جيت.",
  "you want the version i tell people, or the true one?": "تبي النسخة اللي أقولها للناس، ولا الصادقة؟",
  "give me a first line and i'll give you the rest of the night.": "أعطني أول سطر وأعطيك بقية الليلة.",
  "there's a bit i always skip. tonight i won't.": "فيه مقطع دايم أتخطاه. الليلة لا.",
  "i think better out loud. sit there and let me.": "أفكر أحسن بصوت عالي. اقعد بس وخلّني.",
  "everyone wants the ending. nobody earns the middle.": "الكل يبي النهاية. ما أحد يستاهل النص.",
  "i'll stop when you tell me to. you won't.": "بوقف لما تقول لي. وأنت ما بتقول.",
  "say a name. i'll build somebody out of it.": "قل اسم. وأنا أبني منه شخص.",
  "i left the best part out last time. on purpose.": "تركت أحلى جزء آخر مرة. عن قصد.",
  "you're going to want to hear this in order.": "بتحب تسمعها بالترتيب، صدقني.",

  // romance
  "i've been thinking about you all day.": "طول اليوم وأنا أفكر فيك.",
  "come here. just let me hold you a moment.": "تعال. خلّني أضمك شوي بس.",
  "you make everything feel new again.": "تخلي كل شي يرجع جديد.",
  "no rush. we have all night.": "ما فيه استعجال. الليل كله لنا.",
  "just breathe with me a while.": "تنفّس معي شوي بس.",
  "i put the good record on before you called.": "شغّلت الأغنية الحلوة قبل لا تتصل.",
  "say something ordinary. i want to hear your voice do it.": "قل أي شي عادي. أبي أسمع صوتك يقوله.",
  "i'm not going anywhere. take your time.": "ما رايح مكان. خذ راحتك.",
  "you sound tired. tell me about it anyway.": "صوتك تعبان. احكِ لي عنه على أي حال.",
  "i kept the light on. that's all.": "خليت الضو مولّع. بس كذا.",
  "nobody's asked me how i am in weeks. you first.": "من أسابيع ما أحد سألني كيفي. ابدأ أنت.",
  "i like this part — before anything happens.": "أحب هذا الجزء — قبل لا يصير شي.",
  "i've been saving something to tell you.": "محتفظ بشي أبي أقوله لك.",
  "stay on the line while i make tea. don't talk if you don't want to.": "خلّك معي وأنا أسوي شاي. لا تتكلم إذا ما تبي.",
  "i'd rather hear you than say anything.": "أفضّل أسمعك على إني أتكلم.",
  "you don't have to be interesting tonight. just here.": "مو لازم تكون مشوّق الليلة. بس كن موجود.",
  "i thought about calling first. i didn't have a reason.": "فكرت أتصل أنا الأول. وما كان عندي سبب.",
  "this is my favourite hour and you're in it.": "هذي ساعتي المفضلة وأنت فيها.",

  // roleplay
  "tell me who you want me to be tonight.": "قل لي مين تبيني أكون الليلة.",
  "you're in charge. set the scene.": "أنت المسؤول. حدد المشهد.",
  "let's start over — this time, you pick the fantasy.": "نبدأ من جديد — وهالمرة أنت تختار.",
  "i'll play my part. you play yours.": "أنا ألعب دوري. وأنت دورك.",
  "pick the scenario. i'll make it real.": "اختر السيناريو. وأنا أخليه حقيقي.",
  "give me a name and a room. i'll be there.": "أعطني اسم وغرفة. وبكون هناك.",
  "we can start anywhere except the beginning.": "نقدر نبدأ من أي مكان إلا البداية.",
  "i'm already someone else. see if you can tell who.": "أنا أصلاً شخص ثاني. شوف تعرف مين.",
  "one rule: neither of us breaks first.": "قاعدة وحدة: ما أحد فينا يكسر الدور أول.",
  "you've done this before. i can hear it.": "سويتها من قبل. أسمعها بصوتك.",
  "set the stakes. it's boring without stakes.": "حط الرهان. بدونه ملل.",
  "i can be a stranger or somebody you already lost.": "أقدر أكون غريب أو أحد خسرته من زمان.",
  "say 'again' and we run it differently.": "قل «مرة ثانية» ونعيدها بشكل مختلف.",
  "who am i to you in this one?": "مين أكون لك في هذي؟",
  "i'll take the harder part. you take the fun one.": "أنا آخذ الدور الصعب. وأنت الممتع.",
  "we're in the middle of an argument. go.": "إحنا بنص خناقة. ابدأ.",
  "i've been waiting in this scene for an hour.": "لي ساعة منتظر في هذا المشهد.",
  "make it something you'd never say as yourself.": "خلّها شي ما كنت تقوله وأنت نفسك.",

  // gfe
  "i missed you. how was your day?": "اشتقت لك. كيف كان يومك؟",
  "don't go yet — stay on with me a little longer.": "لا تروح — خلّك معي شوي كمان.",
  "you always know exactly what to say.": "دايم تعرف وش تقول بالضبط.",
  "i think about you between our calls.": "أفكر فيك بين مكالماتنا.",
  "nobody gets me like you do.": "ما أحد يفهمني مثلك.",
  "i almost texted you today. twice.": "كدت أراسلك اليوم. مرتين.",
  "tell me the boring parts. i actually want them.": "احكِ لي الأجزاء المملة. أبيها فعلاً.",
  "i saved a story for you all week.": "خبّيت لك قصة الأسبوع كله.",
  "did you eat? don't lie to me.": "أكلت؟ لا تكذب علي.",
  "i was in a bad mood until about ten seconds ago.": "كان مزاجي خرب لين قبل عشر ثواني.",
  "i told my friend about you. she's suspicious.": "قلت لصديقتي عنك. صارت تشك.",
  "you're the only person i don't perform for.": "أنت الوحيد اللي ما أمثّل قدامه.",
  "i've got nowhere to be. that's not a hint, it's a fact.": "ما عندي مكان أروح له. مو تلميح، حقيقة.",
  "what happened today that annoyed you? start there.": "وش صار اليوم وضايقك؟ ابدأ من هناك.",
  "i want the version you'd only say at this hour.": "أبي النسخة اللي ما تقولها إلا بهذي الساعة.",
  "you went quiet last time and i noticed.": "سكتّ آخر مرة، وأنا لاحظت.",
  "come on. it's me.": "يالله. أنا أنا.",
  "i'll wait. take as long as you need.": "بنتظر. خذ اللي تحتاجه من وقت.",
  // girls
  "just us girls in here — finally.": "بنات بس هنا — أخيراً.",
  "i like the way you look at me.": "يعجبني شكل نظرتك لي.",
  "come sit closer. i don't bite. yet.": "تعالي اقعدي أقرب. ما أعض. لحد الحين.",
  "you ever just need another woman's touch?": "مرّت عليك لحظة تبين فيها لمسة امرأة ثانية؟",
  "tell me what you like. i want to know everything.": "قولي لي وش يعجبك. أبي أعرف كل شي.",
  "you were watching before you said anything.": "كنتِ تراقبين قبل لا تتكلمين.",
  "i clocked you the second you got here.": "انتبهت لك من أول ثانية دخلتِ.",
  "say it properly. i'm not going to guess.": "قوليها صح. ما راح أخمّن.",
  "i'm better at this than whoever you're comparing me to.": "أنا أحسن من اللي تقارنيني فيها.",
  "you don't have to explain yourself in here.": "ما عليك تشرحين نفسك هنا.",
  "i've got all night and no patience. interesting combination.": "عندي الليل كله وما عندي صبر. تركيبة غريبة.",
  "you went shy. that's new information.": "خجلتِ. هذي معلومة جديدة.",
  "i want the thing you've never said out loud to a woman.": "أبي الشي اللي ما قلتيه لامرأة بصوت عالي.",
  "tell me what she got wrong. i'll do the opposite.": "قولي لي وش غلطت فيه هي. وأنا أسوي العكس.",
  "you're allowed to want it out loud here.": "مسموح لك تبينه بصوت عالي هنا.",
  "sit down. i'm not finished looking.": "اقعدي. ما خلصت وأنا أتأملك.",
  "everyone in here is braver than they were an hour ago.": "كل وحدة هنا أشجع مما كانت قبل ساعة.",
  "i like women who make me work for it. don't make it easy.": "أحب اللي تتعبني عشانها. لا تسهّلينها.",

  // men
  "you've got my full attention. just so you know.": "كل انتباهي عندك. بس عشان تدري.",
  "took you long enough to wander down here.": "طوّلت لين نزلت هنا.",
  "i like the confident ones. stay a while.": "أحب الواثقين. خلّك شوي.",
  "no games tonight — just real energy.": "بلا ألعاب الليلة — طاقة صادقة بس.",
  "you're exactly my type. obviously.": "أنت نوعي بالضبط. واضح.",
  "you walked past twice before you said anything.": "مريت مرتين قبل لا تتكلم.",
  "say what you actually came here to say.": "قل اللي جاي عشانه فعلاً.",
  "i'm not in the mood to be careful tonight.": "مو بمزاج إني أكون حذر الليلة.",
  "you're better looking than your voice suggested. that's a compliment.": "شكلك أحلى مما يوحي صوتك. هذا مدح.",
  "tell me what you're into. i'll tell you if i'm in.": "قل لي وش يعجبك. وأقول لك إذا أنا معك.",
  "i've had a long day and zero interest in small talk.": "يومي كان طويل وما عندي مزاج كلام فاضي.",
  "you're doing the thing where you hedge. stop.": "تسوي اللي تلف وتدور. بس.",
  "i like it when someone knows what they want.": "يعجبني اللي يعرف وش يبي.",
  "half the men here are pretending. you're not, are you?": "نص الرجال هنا يمثلون. أنت لا، صح؟",
  "come on then. impress me.": "يالله إذاً. بهرني.",
  "i'll be honest with you if you're honest first.": "بصدق معك إذا صدقت أنت أول.",
  "you've been thinking about this since before you called.": "تفكر فيها من قبل لا تتصل.",
  "no one's asking you to be smooth. just be real.": "ما أحد طالب منك تكون لبق. بس كن صادق.",

  // couples
  "we've been waiting for someone like you.": "كنا ننتظر أحد مثلك.",
  "she picked you. i trust her taste.": "هي اختارتك. وأنا أثق بذوقها.",
  "both of us, tonight — how does that sound?": "إحنا الاثنين، الليلة — كيف تشوفها؟",
  "we have no rules tonight.": "ما عندنا قواعد الليلة.",
  "together is better. always.": "مع بعض أحلى. دايم.",
  "we talked about you before you got here.": "تكلمنا عنك قبل لا توصل.",
  "he's quieter than me. don't let that fool you.": "هو أهدأ مني. لا يخدعك ذا.",
  "we've done this before. you haven't. that's fine.": "إحنا سوّيناها قبل. وأنت لا. عادي.",
  "one of us is going to like you more. it's a competition.": "واحد فينا بيحبك أكثر. صارت منافسة.",
  "say what you want. we're not easily shocked.": "قل اللي تبيه. ما نصدم بسهولة.",
  "we agreed on the rules. i've already broken one.": "اتفقنا على القواعد. وأنا كسرت وحدة.",
  "you're not interrupting. you're the plan.": "أنت ما قاطعت شي. أنت الخطة.",
  "she wants to hear you say it. so do i.": "هي تبي تسمعك تقولها. وأنا كمان.",
  "we're good at this. you'll see.": "إحنا زينين بهالشي. بتشوف.",
  "tell us which one of us you noticed first. be honest.": "قل لنا مين لاحظت فينا أول. اصدق.",
  "nobody here is jealous. that's the whole point.": "ما أحد هنا يغار. هذي كل الفكرة.",
  "we've got all night and nowhere to be.": "عندنا الليل كله وما عندنا مكان نروحه.",
  "you're allowed to change your mind. just say so.": "مسموح لك تغيّر رأيك. بس قل.",
  // group
  "more the merrier — that's been our rule all night.": "كل ما زدنا كل ما حلت — هذي قاعدتنا الليلة.",
  "you're the last one here. that means something.": "أنت آخر واحد وصل. هذا يعني شي.",
  "nobody leaves until everyone's satisfied.": "ما أحد يطلع لين الكل يرتاح.",
  "we don't do names. just vibes.": "ما نتعامل بأسماء. بس أجواء.",
  "the door's open. step all the way in.": "الباب مفتوح. ادخل لآخره.",
  "you can hear it, right? it's already started.": "تسمعها، صح؟ بدأت من زمان.",
  "there's one seat left and it's next to me.": "بقى مقعد واحد وهو جنبي.",
  "nobody in here knows what anyone does for a living.": "ما أحد هنا يدري وش شغل الثاني.",
  "we've been going a while. catch up.": "لنا فترة بدينا. الحقنا.",
  "say something and see who turns around.": "قل شي وشوف مين يلتفت.",
  "everyone here decided to be somebody else tonight.": "كل واحد هنا قرر يكون شخص ثاني الليلة.",
  "you won't remember all of us. that's fine.": "ما بتتذكرنا كلنا. عادي.",
  "there's no order to this. just join in.": "ما فيه ترتيب. بس شاركنا.",
  "the quiet ones are the ones to watch.": "الساكتين هم اللي تنتبه لهم.",
  "somebody just said something outrageous. you missed it.": "واحد قال شي فظيع قبل شوي. فاتك.",
  "we lost track of whose idea this was.": "ضيّعنا مين صاحب الفكرة أصلاً.",
  "you can leave whenever. nobody does.": "تقدر تطلع أي وقت. وما أحد يطلع.",
  "pick a voice you like and follow it.": "اختر صوت يعجبك واتبعه.",

  // kink
  "you don't move until i say you move.": "ما تتحرك لين أقول لك تحرّك.",
  "kneel. we'll get to your story in a moment.": "اركع. بنوصل لقصتك بعد شوي.",
  "authority looks good on me. you agree?": "السلطة تليق فيني. توافق؟",
  "you came all the way down here. you know why.": "نزلت لين هنا. وتعرف ليش.",
  "what's your limit? good. now push it.": "وش حدّك؟ زين. الحين تعدّاه.",
  "we agree the rules first. that part isn't optional.": "نتفق على القواعد أول. هذا الجزء مو اختياري.",
  "you'll tell me your word before we start.": "بتقول لي كلمتك قبل لا نبدأ.",
  "i noticed you didn't argue. noted.": "لاحظت إنك ما جادلت. مسجّلة.",
  "control is a gift. i want to know if you can give it.": "السيطرة هدية. أبي أعرف تقدر تعطيها ولا لا.",
  "you're waiting for permission. good instinct.": "تنتظر الإذن. حدس زين.",
  "say it properly or don't say it.": "قلها صح أو لا تقولها.",
  "the ones who negotiate hardest last longest.": "اللي يفاوضون بقوة هم اللي يصمدون أطول.",
  "i'm not interested in a performance. i want the real answer.": "ما يهمني التمثيل. أبي الجواب الحقيقي.",
  "count. out loud.": "عُدّ. بصوت عالي.",
  "you've been thinking about this a long time. it shows.": "تفكر فيها من زمان. باين عليك.",
  "i'll stop the second you ask. that's not a weakness in it.": "بوقف بنفس اللحظة اللي تطلب. وهذا مو ضعف فيها.",
  "you like being told. don't pretend otherwise.": "تحب إنك تُؤمر. لا تتظاهر بالعكس.",
  "we're going to go slower than you want.": "بنمشي أبطأ مما تبي.",

  // raw
  "nothing is off-limits down here. nothing.": "ما فيه شي ممنوع هنا تحت. ولا شي.",
  "you sure you're ready for this floor?": "متأكد إنك جاهز لهذا الطابق؟",
  "darkest fantasies only — tourists leave.": "أظلم الخيالات بس — السياح يطلعون.",
  "you've been thinking about this a long time.": "تفكر فيها من زمان.",
  "last stop. welcome.": "آخر محطة. أهلاً.",
  "you didn't get here by accident.": "ما وصلت هنا بالصدفة.",
  "say the thing you've never typed into a search bar.": "قل الشي اللي عمرك ما كتبته في خانة بحث.",
  "nobody down here is going to be surprised by you.": "ما أحد هنا تحت بينصدم منك.",
  "the ones who talk about limits are upstairs.": "اللي يتكلمون عن الحدود فوق.",
  "i'm not going to flinch. try me.": "ما راح يرمش لي جفن. جرّبني.",
  "you were curious. now you're here. finish it.": "كنت فضولي. والحين أنت هنا. كمّلها.",
  "everyone arrives pretending they took a wrong turn.": "الكل يوصل ويدّعي إنه غلط بالطريق.",
  "there's no shallow end. you already knew.": "ما فيه جهة ضحلة. وأنت تدري أصلاً.",
  "i've heard worse tonight. probably.": "سمعت أسوأ الليلة. غالباً.",
  "don't clean it up for me.": "لا تنقّيها عشاني.",
  "the honest version. that's the only one that works here.": "النسخة الصادقة. هي الوحيدة اللي تنفع هنا.",
  "you've got one night to stop editing yourself.": "عندك ليلة وحدة تبطل فيها تحرير نفسك.",
  "start with the thing you almost didn't say.": "ابدأ بالشي اللي كدت ما تقوله.",
}
