import type { Metadata } from "next"

export const metadata: Metadata = { title: "Terms — AIRRAW", alternates: { canonical: "https://airraw.com/airraw/terms" } }

const wrap: React.CSSProperties = { minHeight: "100vh", background: "#06070e", color: "#cdd9e3", padding: "48px 22px 80px", maxWidth: 680, margin: "0 auto", lineHeight: 1.65, fontSize: 15 }
const h1: React.CSSProperties = { fontSize: 26, fontWeight: 600, color: "#eef4f8", letterSpacing: 1 }
const h2: React.CSSProperties = { fontSize: 16, fontWeight: 600, color: "#eef4f8", marginTop: 26 }

export default function Terms() {
  return (
    <div style={wrap}>
      <a href="/airraw" style={{ fontSize: 13, color: "#7fd6c0", textDecoration: "none" }}>← airraw</a>
      <h1 style={{ ...h1, marginTop: 14 }}>Terms</h1>
      <p style={{ color: "#7f93a5", fontSize: 13 }}>Last updated June 2026</p>

      <h2 style={h2}>What this is</h2>
      <p>AIRRAW is a live voice and text lounge where you talk with AI characters — and, in shared rooms, with real people. It&apos;s for entertainment.</p>

      <h2 style={h2}>Using it</h2>
      <p>You must be 18 or older to enter the adult areas. Don&apos;t use AIRRAW for anything illegal, and don&apos;t harass or abuse other people in the rooms. We can remove access for abuse.</p>

      <h2 style={h2}>The AI can be wrong</h2>
      <p>Replies are generated by AI and may be inaccurate or made up. Don&apos;t rely on anything here as professional, legal, medical, or financial advice.</p>

      <h2 style={h2}>Money</h2>
      <p>Founding access is free. A $1 day-pass is coming; if and when you pay, the price and terms will be shown before you&apos;re charged.</p>

      <h2 style={h2}>As-is</h2>
      <p>AIRRAW is provided as-is, without warranties, while we&apos;re building. We may change or pause the service.</p>

      <h2 style={h2}>Contact</h2>
      <p><a href="mailto:hello@airraw.com" style={{ color: "#7fd6c0" }}>hello@airraw.com</a></p>
    </div>
  )
}
